#!/bin/sh
set -eu

system_bundle=/opt/aegisos/tor-browser
user_bundle="${XDG_DATA_HOME:-$HOME/.local/share}/aegisos/tor-browser"

if [ ! -x "$user_bundle/Browser/start-tor-browser" ]; then
  install -d "$(dirname "$user_bundle")"
  staging="$user_bundle.new.$$"
  trap 'rm -rf -- "$staging"' EXIT HUP INT TERM
  cp -R --preserve=mode,timestamps "$system_bundle" "$staging"
  mv "$staging" "$user_bundle"
  trap - EXIT HUP INT TERM
fi

exec "$user_bundle/Browser/start-tor-browser" --detach "$@"
