efiSystemPartition: "/boot/efi"
enableLuksAutomatedPartitioning: true
preCheckEncryption: true
luksGeneration: luks2
initialPartitioningChoice: none
allowManualPartitioning: false
userSwapChoices:
    - none
    - file
initialSwapChoice: file
drawNestedPartitions: true
alwaysShowPartitionLabels: true
defaultFileSystemType: "ext4"
availableFileSystemTypes: ["ext4", "btrfs", "xfs"]
partitionLayout:
    - name: "aegisos_boot"
      filesystem: ext4
      noEncrypt: true
      onlyPresentWithEncryption: true
      mountPoint: "/boot"
      size: 2G
    - name: "aegisos_root"
      filesystem: unknown
      mountPoint: "/"
      size: 100%
